services:
  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  php:
    build:
      dockerfile: php/Dockerfile
    volumes:
      - ../../:/var/www/html

  database:
    build:
      dockerfile: database/Dockerfile

    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: srims
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:
    driver: local