nelmio_api_doc:
  documentation:
    host:
    schemes: [http, https]
    info:
      title: A Very Simple Recipe And Ingredient Management System
      description:
      version: 1.0.0
    security_definitions:
      api_key:
        type: apiKey
        description: Your Token
        name: Authorization
        in: header
      security:
        api_key: [ ]
  areas:
    default:
      path_patterns: [ ^/api ]
