FROM php:8.2-fpm

RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install ctype
RUN docker-php-ext-install iconv
#RUN docker-php-ext-install pcre
RUN docker-php-ext-install session
#RUN docker-php-ext-install simplexml
#RUN docker-php-ext-install tokenizer

