ingredient:
  resource: 'routes/ingredient.yaml'
  prefix: /ingredient

recipe:
  resource: 'routes/recipe.yaml'
  prefix: /recipe

login_route:
  path: /login
  methods: POST
  controller: App\Controller\AuthenticationController::login
